import pytest
from fastapi.testclient import TestClient
from sqlalchemy import text
from sqlalchemy.exc import OperationalError

from app.core.config import settings
from app.main import app
from app.storage.db import engine, init_db, clear_db, SessionLocal

client = TestClient(app)


@pytest.fixture(scope="module")
def rag_setup():
    # 1. Skip if database is not available
    try:
        with engine.connect() as conn:
            conn.execute(text("SELECT 1;"))
    except OperationalError as e:
        pytest.skip(f"Local database is not available: {e}")

    # 2. Skip if Azure OpenAI is not configured
    if not settings.AZURE_OPENAI_ENDPOINT or not settings.AZURE_OPENAI_API_KEY:
        pytest.skip(
            "Azure OpenAI credentials are not configured. Setup AZURE_OPENAI_ENDPOINT and AZURE_OPENAI_API_KEY in .env."
        )

    # 3. Initialize tables
    init_db()

    yield

    # 4. Clean up tables
    clear_db()


def test_end_to_end_rag_flow(rag_setup):
    # Step A: Ingest a sample corporate document chunk
    ingest_payload = {
        "title": "Corporate Firewall Protocols",
        "source_type": "local",
        "source_uri": "file://network/firewall.txt",
        "document_type": "protocol",
        "content": "The firewall protocol dictates that port 22 (SSH) must only be accessible from the internal corporate VPN (subnet 10.0.0.0/8). Incoming public traffic to port 22 must be automatically dropped.",
        "language": "en",
        "security_acl": {"allowed_groups": ["Engineering"]},
        "metadata_json": {"version": "v1.2", "classification": "restricted"},
    }

    ingest_response = client.post("/api/documents/ingest", json=ingest_payload)
    assert ingest_response.status_code == 200
    ingest_data = ingest_response.json()
    assert ingest_data["status"] == "ingested"
    assert ingest_data["title"] == "Corporate Firewall Protocols"
    assert "document_id" in ingest_data

    # Step B: Submit a RAG query matching the document topic
    chat_payload = {
        "query": "Which subnet is allowed to access port 22 according to the firewall protocols?",
        "mode": "flash",
        "filters": {"classification": "restricted"},
        "include_sources": True,
        "search_strategy": "vector",
    }

    chat_response = client.post(
        "/api/chat",
        json=chat_payload,
        headers={"X-User-Groups": "Engineering"}
    )
    assert chat_response.status_code == 200
    chat_data = chat_response.json()

    # Step C: Assert answers and citations
    # The answer should be generated by gpt-5.4-mini and grounded in the ingested content.
    assert "answer" in chat_data
    assert len(chat_data["answer"]) > 10
    
    # Check that sources and citations are present
    assert len(chat_data["sources"]) >= 1
    assert chat_data["sources"][0]["title"] == "Corporate Firewall Protocols"
    assert chat_data["metadata"]["retrieval_strategy"] == "vector_pgvector"
    assert "latency_ms" in chat_data["metadata"]
